#if UNITY_EDITOR
using UnityEngine;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine.UI;
using TMPro;

/// <summary>
/// Editor script: Tools → Build Pause Menu
/// Automatically generates a complete Pause Menu UI in the current scene.
/// Creates a Canvas with Resume, Settings, Main Menu, Wipe Data, and Quit buttons,
/// plus a full Settings sub-panel — all wired to PauseManager and SettingsMenu.
/// Re-runnable: deletes the old one and rebuilds fresh each time.
/// </summary>
public class PauseMenuBuilder : Editor
{
    // --- DOOM-esque dark theme ---
    private static readonly Color panelColor = new Color(0.08f, 0.06f, 0.1f, 0.96f);
    private static readonly Color accentRed = new Color(0.85f, 0.15f, 0.1f, 1f);
    private static readonly Color accentOrange = new Color(1f, 0.5f, 0.1f, 1f);
    private static readonly Color textWhite = new Color(0.95f, 0.92f, 0.88f, 1f);
    private static readonly Color buttonBg = new Color(0.12f, 0.1f, 0.14f, 0.95f);
    private static readonly Color buttonHover = new Color(0.9f, 0.25f, 0.15f, 1f);
    private static readonly Color subtleGray = new Color(0.6f, 0.55f, 0.5f, 1f);
    private static readonly Color dangerRed = new Color(0.7f, 0.1f, 0.1f, 1f);

    [MenuItem("Tools/Build Pause Menu")]
    public static void BuildPauseMenu()
    {
        // --- Determine parent: selected object (e.g. PlayerRig) or scene root ---
        Transform parentTransform = null;
        if (Selection.activeGameObject != null)
        {
            parentTransform = Selection.activeGameObject.transform;
            Debug.Log($"[PauseMenuBuilder] Building inside selected object: {Selection.activeGameObject.name}");
        }
        else
        {
            Debug.Log("[PauseMenuBuilder] No object selected — building at scene root. " +
                      "TIP: Select your PlayerRig first to build inside it.");
        }

        // --- Cleanup: Remove existing auto-generated pause menu ---
        // Search inside the parent if we have one, otherwise globally
        GameObject existing = null;
        if (parentTransform != null)
        {
            Transform found = parentTransform.Find("PauseMenuCanvas_AutoGenerated");
            if (found != null) existing = found.gameObject;
        }
        if (existing == null)
            existing = GameObject.Find("PauseMenuCanvas_AutoGenerated");
        
        if (existing != null)
        {
            Undo.DestroyObjectImmediate(existing);
            Debug.Log("[PauseMenuBuilder] Removed old auto-generated pause menu.");
        }

        // --- Find PauseManager (prefer inside selected hierarchy) ---
        PauseManager pauseManager = null;
        if (parentTransform != null)
            pauseManager = parentTransform.GetComponentInChildren<PauseManager>(true);
        if (pauseManager == null)
            pauseManager = FindFirstObjectByType<PauseManager>();
        if (pauseManager == null)
        {
            // Create PauseManager as sibling inside the parent hierarchy
            GameObject pmObj = new GameObject("PauseManager");
            if (parentTransform != null)
                pmObj.transform.SetParent(parentTransform, false);
            Undo.RegisterCreatedObjectUndo(pmObj, "Create PauseManager");
            pauseManager = pmObj.AddComponent<PauseManager>();
        }

        // --- Find CursorManager (prefer inside selected hierarchy) ---
        CursorManager cursorManager = null;
        if (parentTransform != null)
            cursorManager = parentTransform.GetComponentInChildren<CursorManager>(true);
        if (cursorManager == null)
            cursorManager = FindFirstObjectByType<CursorManager>();
        if (cursorManager == null)
        {
            GameObject cmObj = new GameObject("CursorManager");
            if (parentTransform != null)
                cmObj.transform.SetParent(parentTransform, false);
            Undo.RegisterCreatedObjectUndo(cmObj, "Create CursorManager");
            cursorManager = cmObj.AddComponent<CursorManager>();
        }

        // Wire cursor manager
        var cmField = pauseManager.GetType().GetField("cursorManager",
            System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance);
        if (cmField != null) cmField.SetValue(pauseManager, cursorManager);

        // ==========================================
        // CANVAS (parented inside selected object for prefab support)
        // ==========================================
        GameObject canvasObj = new GameObject("PauseMenuCanvas_AutoGenerated");
        if (parentTransform != null)
            canvasObj.transform.SetParent(parentTransform, false);
        Undo.RegisterCreatedObjectUndo(canvasObj, "Create Pause Menu Canvas");
        Canvas canvas = canvasObj.AddComponent<Canvas>();
        canvas.renderMode = RenderMode.ScreenSpaceOverlay;
        canvas.sortingOrder = 200; // Above game HUD
        CanvasScaler scaler = canvasObj.AddComponent<CanvasScaler>();
        scaler.uiScaleMode = CanvasScaler.ScaleMode.ScaleWithScreenSize;
        scaler.referenceResolution = new Vector2(1920, 1080);
        scaler.matchWidthOrHeight = 0.5f;
        canvasObj.AddComponent<GraphicRaycaster>();

        // ==========================================
        // FULL-SCREEN DIM OVERLAY
        // ==========================================
        GameObject dimOverlay = new GameObject("DimOverlay");
        dimOverlay.transform.SetParent(canvasObj.transform, false);
        RectTransform dimRt = dimOverlay.AddComponent<RectTransform>();
        dimRt.anchorMin = Vector2.zero;
        dimRt.anchorMax = Vector2.one;
        dimRt.sizeDelta = Vector2.zero;
        Image dimImg = dimOverlay.AddComponent<Image>();
        dimImg.color = new Color(0f, 0f, 0f, 0.6f);
        dimImg.raycastTarget = true; // Block clicks through to game

        // ==========================================
        // PAUSE PANEL
        // ==========================================
        GameObject pausePanel = CreatePanel(canvasObj.transform, "PausePanel", Vector2.zero, new Vector2(500, 550));

        // Title
        CreateText(pausePanel.transform, "PauseTitle", "|| PAUSED",
            new Vector2(0, 200), new Vector2(400, 60), 32, accentRed, FontStyles.Bold, TextAlignmentOptions.Center);

        // Separator line
        GameObject sep = new GameObject("Separator");
        sep.transform.SetParent(pausePanel.transform, false);
        RectTransform sepRt = sep.AddComponent<RectTransform>();
        sepRt.anchorMin = new Vector2(0.5f, 0.5f);
        sepRt.anchorMax = new Vector2(0.5f, 0.5f);
        sepRt.anchoredPosition = new Vector2(0, 155);
        sepRt.sizeDelta = new Vector2(350, 2);
        sep.AddComponent<Image>().color = accentRed * 0.5f;

        // Buttons
        float y = 100f;
        float step = -65f;

        GameObject resumeBtn = CreateButton(pausePanel.transform, "ResumeButton", "> RESUME",
            new Vector2(0, y), new Vector2(320, 55), buttonBg, textWhite, 22);
        y += step;

        GameObject settingsBtn = CreateButton(pausePanel.transform, "SettingsButton", "SETTINGS",
            new Vector2(0, y), new Vector2(320, 55), buttonBg, textWhite, 20);
        y += step;

        GameObject mainMenuBtn = CreateButton(pausePanel.transform, "MainMenuButton", "MAIN MENU",
            new Vector2(0, y), new Vector2(320, 55), buttonBg, subtleGray, 20);
        y += step;

        GameObject wipeBtn = CreateButton(pausePanel.transform, "WipeDataButton", "WIPE DATA",
            new Vector2(0, y), new Vector2(320, 55), buttonBg, dangerRed, 18);
        y += step;

        GameObject quitBtn = CreateButton(pausePanel.transform, "QuitButton", "QUIT GAME",
            new Vector2(0, y), new Vector2(320, 55), dangerRed, textWhite, 20);

        // ==========================================
        // SETTINGS SUB-PANEL
        // ==========================================
        GameObject settingsPanel = CreatePanel(canvasObj.transform, "SettingsPanel", Vector2.zero, new Vector2(700, 800));
        SettingsMenu settingsMenuComp = settingsPanel.AddComponent<SettingsMenu>();
        settingsMenuComp.settingsPanel = settingsPanel;
        settingsPanel.SetActive(false);

        // Settings title
        CreateText(settingsPanel.transform, "SettingsTitle", "SETTINGS",
            new Vector2(0, 330), new Vector2(400, 50), 28, accentOrange, FontStyles.Bold, TextAlignmentOptions.Center);

        float sy = 260f;
        float sStep = -65f;

        // Sensitivity
        var sens = CreateSliderRow(settingsPanel.transform, "Sensitivity", sy);
        settingsMenuComp.sensitivitySlider = sens.slider;
        settingsMenuComp.sensitivityValueText = sens.valueText;
        sy += sStep;

        // Master Volume
        var master = CreateSliderRow(settingsPanel.transform, "Master Volume", sy);
        settingsMenuComp.masterVolumeSlider = master.slider;
        settingsMenuComp.masterVolumeValueText = master.valueText;
        sy += sStep;

        // Music Volume
        var music = CreateSliderRow(settingsPanel.transform, "Music Volume", sy);
        settingsMenuComp.musicVolumeSlider = music.slider;
        settingsMenuComp.musicVolumeValueText = music.valueText;
        sy += sStep;

        // SFX Volume
        var sfx = CreateSliderRow(settingsPanel.transform, "SFX Volume", sy);
        settingsMenuComp.sfxVolumeSlider = sfx.slider;
        settingsMenuComp.sfxVolumeValueText = sfx.valueText;
        sy += sStep;

        // FOV
        var fov = CreateSliderRow(settingsPanel.transform, "Field of View", sy);
        settingsMenuComp.fovSlider = fov.slider;
        settingsMenuComp.fovValueText = fov.valueText;
        sy += sStep;

        // View Bob Toggle
        var viewBobToggle = CreateToggleRow(settingsPanel.transform, "View Bob", sy);
        settingsMenuComp.viewBobToggle = viewBobToggle;
        sy += sStep;

        // Fullscreen Toggle
        var fullscreenToggle = CreateToggleRow(settingsPanel.transform, "Fullscreen", sy);
        settingsMenuComp.fullscreenToggle = fullscreenToggle;
        sy += sStep;

        // Quality Dropdown
        var quality = CreateDropdownRow(settingsPanel.transform, "Quality", sy);
        settingsMenuComp.qualityDropdown = quality;
        sy += sStep;

        // Reset Defaults
        GameObject resetBtn = CreateButton(settingsPanel.transform, "ResetButton", "RESET DEFAULTS",
            new Vector2(0, sy), new Vector2(250, 45), buttonBg, accentOrange, 16);
        sy += sStep;

        // Back button
        GameObject settingsBackBtn = CreateButton(settingsPanel.transform, "SettingsBackButton", "← BACK",
            new Vector2(0, sy), new Vector2(200, 45), buttonBg, subtleGray, 16);

        // ==========================================
        // WIRE UP PauseManager
        // ==========================================
        // pauseCanvas = entire canvas root (for show/hide on pause/resume)
        var pauseCanvasField = pauseManager.GetType().GetField("pauseCanvas",
            System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance);
        if (pauseCanvasField != null) pauseCanvasField.SetValue(pauseManager, canvasObj);

        // pauseMenuUI = just the buttons panel (so settings can show while this is hidden)
        var pauseMenuField = pauseManager.GetType().GetField("pauseMenuUI",
            System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance);
        if (pauseMenuField != null) pauseMenuField.SetValue(pauseManager, pausePanel);

        var settingsMenuField = pauseManager.GetType().GetField("settingsMenu",
            System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance);
        if (settingsMenuField != null) settingsMenuField.SetValue(pauseManager, settingsMenuComp);

        // ==========================================
        // WIRE UP BUTTON EVENTS
        // ==========================================
        UnityEditor.Events.UnityEventTools.AddPersistentListener(
            resumeBtn.GetComponent<Button>().onClick, pauseManager.Resume);

        UnityEditor.Events.UnityEventTools.AddPersistentListener(
            settingsBtn.GetComponent<Button>().onClick, pauseManager.OpenSettings);

        UnityEditor.Events.UnityEventTools.AddPersistentListener(
            mainMenuBtn.GetComponent<Button>().onClick, pauseManager.ReturnToMainMenu);

        UnityEditor.Events.UnityEventTools.AddPersistentListener(
            wipeBtn.GetComponent<Button>().onClick, pauseManager.WipeData);

        UnityEditor.Events.UnityEventTools.AddPersistentListener(
            quitBtn.GetComponent<Button>().onClick, pauseManager.QuitGame);

        UnityEditor.Events.UnityEventTools.AddPersistentListener(
            resetBtn.GetComponent<Button>().onClick, settingsMenuComp.ResetDefaults);

        UnityEditor.Events.UnityEventTools.AddPersistentListener(
            settingsBackBtn.GetComponent<Button>().onClick, pauseManager.CloseSettings);

        // Start hidden (PauseManager shows it on Escape)
        canvasObj.SetActive(false);

        // Mark dirty
        EditorSceneManager.MarkSceneDirty(EditorSceneManager.GetActiveScene());
        EditorUtility.SetDirty(pauseManager);

        Selection.activeGameObject = canvasObj;

        string parentName = parentTransform != null ? parentTransform.gameObject.name : "scene root";
        EditorUtility.DisplayDialog("Pause Menu Built! ✅",
            $"Auto-generated Pause Menu added inside: {parentName}\n\n" +
            "Includes: Resume, Settings, Main Menu, Wipe Data, Quit.\n" +
            "Settings panel has: Sensitivity, Volume, FOV, View Bob, Fullscreen, Quality.\n\n" +
            "TIP: Select your PlayerRig first, then run this tool to keep it inside the prefab.\n" +
            "Re-run anytime to rebuild the pause menu fresh!",
            "Got it!");

        Debug.Log("[PauseMenuBuilder] Pause menu created and wired up.");
    }

    // ==========================================
    // HELPERS (same style as MainMenuBuilder)
    // ==========================================

    static GameObject CreatePanel(Transform parent, string name, Vector2 position, Vector2 size)
    {
        GameObject panel = new GameObject(name);
        panel.transform.SetParent(parent, false);
        RectTransform rt = panel.AddComponent<RectTransform>();
        rt.anchorMin = new Vector2(0.5f, 0.5f);
        rt.anchorMax = new Vector2(0.5f, 0.5f);
        rt.anchoredPosition = position;
        rt.sizeDelta = size;
        Image img = panel.AddComponent<Image>();
        img.color = panelColor;
        panel.AddComponent<CanvasGroup>();
        return panel;
    }

    static TextMeshProUGUI CreateText(Transform parent, string name, string content,
        Vector2 position, Vector2 size, int fontSize, Color color, FontStyles style, TextAlignmentOptions alignment)
    {
        GameObject textObj = new GameObject(name);
        textObj.transform.SetParent(parent, false);
        RectTransform rt = textObj.AddComponent<RectTransform>();
        rt.anchorMin = new Vector2(0.5f, 0.5f);
        rt.anchorMax = new Vector2(0.5f, 0.5f);
        rt.anchoredPosition = position;
        rt.sizeDelta = size;
        TextMeshProUGUI tmp = textObj.AddComponent<TextMeshProUGUI>();
        tmp.text = content;
        tmp.fontSize = fontSize;
        tmp.color = color;
        tmp.fontStyle = style;
        tmp.alignment = alignment;
        return tmp;
    }

    static GameObject CreateButton(Transform parent, string name, string label,
        Vector2 position, Vector2 size, Color bgColor, Color textColor, int fontSize)
    {
        GameObject btnObj = new GameObject(name);
        btnObj.transform.SetParent(parent, false);
        RectTransform rt = btnObj.AddComponent<RectTransform>();
        rt.anchorMin = new Vector2(0.5f, 0.5f);
        rt.anchorMax = new Vector2(0.5f, 0.5f);
        rt.anchoredPosition = position;
        rt.sizeDelta = size;
        Image img = btnObj.AddComponent<Image>();
        img.color = bgColor;
        Button btn = btnObj.AddComponent<Button>();
        ColorBlock colors = btn.colors;
        colors.normalColor = bgColor;
        colors.highlightedColor = buttonHover;
        colors.pressedColor = accentRed;
        colors.selectedColor = bgColor;
        btn.colors = colors;
        CreateText(btnObj.transform, name + "_Text", label,
            Vector2.zero, size, fontSize, textColor, FontStyles.Bold, TextAlignmentOptions.Center);
        return btnObj;
    }

    struct SliderRow { public Slider slider; public TextMeshProUGUI valueText; }

    static SliderRow CreateSliderRow(Transform parent, string label, float yPos)
    {
        GameObject row = new GameObject(label.Replace(" ", "") + "Row");
        row.transform.SetParent(parent, false);
        RectTransform rowRt = row.AddComponent<RectTransform>();
        rowRt.anchorMin = new Vector2(0.5f, 0.5f);
        rowRt.anchorMax = new Vector2(0.5f, 0.5f);
        rowRt.anchoredPosition = new Vector2(0, yPos);
        rowRt.sizeDelta = new Vector2(600, 50);

        CreateText(row.transform, label.Replace(" ", "") + "Label", label,
            new Vector2(-200, 0), new Vector2(180, 40), 16, textWhite, FontStyles.Normal, TextAlignmentOptions.Left);

        GameObject sliderObj = CreateDefaultSlider(row.transform, label.Replace(" ", "") + "Slider",
            new Vector2(40, 0), new Vector2(250, 30));
        Slider slider = sliderObj.GetComponent<Slider>();

        TextMeshProUGUI valueText = CreateText(row.transform, label.Replace(" ", "") + "Value", "0",
            new Vector2(220, 0), new Vector2(80, 40), 14, accentOrange, FontStyles.Normal, TextAlignmentOptions.Center);

        return new SliderRow { slider = slider, valueText = valueText };
    }

    static GameObject CreateDefaultSlider(Transform parent, string name, Vector2 pos, Vector2 size)
    {
        GameObject sliderObj = new GameObject(name);
        sliderObj.transform.SetParent(parent, false);
        RectTransform rt = sliderObj.AddComponent<RectTransform>();
        rt.anchorMin = new Vector2(0.5f, 0.5f);
        rt.anchorMax = new Vector2(0.5f, 0.5f);
        rt.anchoredPosition = pos;
        rt.sizeDelta = size;

        Slider slider = sliderObj.AddComponent<Slider>();
        slider.minValue = 0; slider.maxValue = 1; slider.value = 0.5f;

        GameObject bg = new GameObject("Background");
        bg.transform.SetParent(sliderObj.transform, false);
        RectTransform bgRt = bg.AddComponent<RectTransform>();
        bgRt.anchorMin = Vector2.zero; bgRt.anchorMax = Vector2.one; bgRt.sizeDelta = Vector2.zero;
        bg.AddComponent<Image>().color = new Color(0.15f, 0.12f, 0.18f, 1f);

        GameObject fillArea = new GameObject("Fill Area");
        fillArea.transform.SetParent(sliderObj.transform, false);
        RectTransform fillAreaRt = fillArea.AddComponent<RectTransform>();
        fillAreaRt.anchorMin = new Vector2(0, 0.25f); fillAreaRt.anchorMax = new Vector2(1, 0.75f);
        fillAreaRt.offsetMin = new Vector2(5, 0); fillAreaRt.offsetMax = new Vector2(-5, 0);

        GameObject fill = new GameObject("Fill");
        fill.transform.SetParent(fillArea.transform, false);
        RectTransform fillRt = fill.AddComponent<RectTransform>();
        fillRt.anchorMin = Vector2.zero; fillRt.anchorMax = Vector2.one; fillRt.sizeDelta = Vector2.zero;
        fill.AddComponent<Image>().color = accentRed;

        GameObject handleArea = new GameObject("Handle Slide Area");
        handleArea.transform.SetParent(sliderObj.transform, false);
        RectTransform handleAreaRt = handleArea.AddComponent<RectTransform>();
        handleAreaRt.anchorMin = Vector2.zero; handleAreaRt.anchorMax = Vector2.one;
        handleAreaRt.offsetMin = new Vector2(10, 0); handleAreaRt.offsetMax = new Vector2(-10, 0);

        GameObject handle = new GameObject("Handle");
        handle.transform.SetParent(handleArea.transform, false);
        RectTransform handleRt = handle.AddComponent<RectTransform>();
        handleRt.sizeDelta = new Vector2(20, 0);
        Image handleImg = handle.AddComponent<Image>();
        handleImg.color = textWhite;

        slider.fillRect = fillRt;
        slider.handleRect = handleRt;
        slider.targetGraphic = handleImg;

        return sliderObj;
    }

    static Toggle CreateToggleRow(Transform parent, string label, float yPos)
    {
        GameObject row = new GameObject(label.Replace(" ", "") + "Row");
        row.transform.SetParent(parent, false);
        RectTransform rowRt = row.AddComponent<RectTransform>();
        rowRt.anchorMin = new Vector2(0.5f, 0.5f);
        rowRt.anchorMax = new Vector2(0.5f, 0.5f);
        rowRt.anchoredPosition = new Vector2(0, yPos);
        rowRt.sizeDelta = new Vector2(600, 50);

        CreateText(row.transform, label + "Label", label,
            new Vector2(-200, 0), new Vector2(180, 40), 16, textWhite, FontStyles.Normal, TextAlignmentOptions.Left);

        GameObject toggleObj = new GameObject(label.Replace(" ", "") + "Toggle");
        toggleObj.transform.SetParent(row.transform, false);
        RectTransform toggleRt = toggleObj.AddComponent<RectTransform>();
        toggleRt.anchorMin = new Vector2(0.5f, 0.5f);
        toggleRt.anchorMax = new Vector2(0.5f, 0.5f);
        toggleRt.anchoredPosition = new Vector2(40, 0);
        toggleRt.sizeDelta = new Vector2(40, 40);

        Toggle toggle = toggleObj.AddComponent<Toggle>();

        GameObject bgObj = new GameObject("Background");
        bgObj.transform.SetParent(toggleObj.transform, false);
        RectTransform bgRt = bgObj.AddComponent<RectTransform>();
        bgRt.anchorMin = Vector2.zero; bgRt.anchorMax = Vector2.one; bgRt.sizeDelta = Vector2.zero;
        Image bgImg = bgObj.AddComponent<Image>();
        bgImg.color = new Color(0.15f, 0.12f, 0.18f, 1f);
        toggle.targetGraphic = bgImg;

        GameObject checkObj = new GameObject("Checkmark");
        checkObj.transform.SetParent(bgObj.transform, false);
        RectTransform checkRt = checkObj.AddComponent<RectTransform>();
        checkRt.anchorMin = new Vector2(0.1f, 0.1f); checkRt.anchorMax = new Vector2(0.9f, 0.9f);
        checkRt.sizeDelta = Vector2.zero;
        Image checkImg = checkObj.AddComponent<Image>();
        checkImg.color = accentRed;
        toggle.graphic = checkImg;

        return toggle;
    }

    static TMP_Dropdown CreateDropdownRow(Transform parent, string label, float yPos)
    {
        GameObject row = new GameObject(label + "Row");
        row.transform.SetParent(parent, false);
        RectTransform rowRt = row.AddComponent<RectTransform>();
        rowRt.anchorMin = new Vector2(0.5f, 0.5f);
        rowRt.anchorMax = new Vector2(0.5f, 0.5f);
        rowRt.anchoredPosition = new Vector2(0, yPos);
        rowRt.sizeDelta = new Vector2(600, 50);

        CreateText(row.transform, label + "Label", label,
            new Vector2(-200, 0), new Vector2(180, 40), 16, textWhite, FontStyles.Normal, TextAlignmentOptions.Left);

        GameObject dropObj = new GameObject(label + "Dropdown");
        dropObj.transform.SetParent(row.transform, false);
        RectTransform dropRt = dropObj.AddComponent<RectTransform>();
        dropRt.anchorMin = new Vector2(0.5f, 0.5f);
        dropRt.anchorMax = new Vector2(0.5f, 0.5f);
        dropRt.anchoredPosition = new Vector2(40, 0);
        dropRt.sizeDelta = new Vector2(250, 40);

        dropObj.AddComponent<Image>().color = new Color(0.15f, 0.12f, 0.18f, 1f);
        TMP_Dropdown dropdown = dropObj.AddComponent<TMP_Dropdown>();

        TextMeshProUGUI captionText = CreateText(dropObj.transform, "CaptionText", "Select...",
            Vector2.zero, new Vector2(230, 35), 14, textWhite, FontStyles.Normal, TextAlignmentOptions.Left);
        dropdown.captionText = captionText;

        // Template
        GameObject template = new GameObject("Template");
        template.transform.SetParent(dropObj.transform, false);
        RectTransform tempRt = template.AddComponent<RectTransform>();
        tempRt.anchorMin = new Vector2(0, 0); tempRt.anchorMax = new Vector2(1, 0);
        tempRt.pivot = new Vector2(0.5f, 1f);
        tempRt.anchoredPosition = Vector2.zero; tempRt.sizeDelta = new Vector2(0, 150);
        template.AddComponent<Image>().color = panelColor;

        GameObject viewport = new GameObject("Viewport");
        viewport.transform.SetParent(template.transform, false);
        RectTransform vpRt = viewport.AddComponent<RectTransform>();
        vpRt.anchorMin = Vector2.zero; vpRt.anchorMax = Vector2.one; vpRt.sizeDelta = Vector2.zero;
        viewport.AddComponent<Image>().color = panelColor;
        viewport.AddComponent<Mask>().showMaskGraphic = false;

        GameObject content = new GameObject("Content");
        content.transform.SetParent(viewport.transform, false);
        RectTransform contentRt = content.AddComponent<RectTransform>();
        contentRt.anchorMin = new Vector2(0, 1); contentRt.anchorMax = Vector2.one;
        contentRt.pivot = new Vector2(0.5f, 1f); contentRt.sizeDelta = new Vector2(0, 28);

        GameObject item = new GameObject("Item");
        item.transform.SetParent(content.transform, false);
        RectTransform itemRt = item.AddComponent<RectTransform>();
        itemRt.anchorMin = new Vector2(0, 0.5f); itemRt.anchorMax = new Vector2(1, 0.5f);
        itemRt.sizeDelta = new Vector2(0, 28);

        Toggle itemToggle = item.AddComponent<Toggle>();

        GameObject itemBg = new GameObject("Item Background");
        itemBg.transform.SetParent(item.transform, false);
        RectTransform itemBgRt = itemBg.AddComponent<RectTransform>();
        itemBgRt.anchorMin = Vector2.zero; itemBgRt.anchorMax = Vector2.one; itemBgRt.sizeDelta = Vector2.zero;
        Image itemBgImg = itemBg.AddComponent<Image>();
        itemBgImg.color = new Color(0.15f, 0.12f, 0.18f, 0.5f);

        GameObject itemCheck = new GameObject("Item Checkmark");
        itemCheck.transform.SetParent(item.transform, false);
        RectTransform itemCheckRt = itemCheck.AddComponent<RectTransform>();
        itemCheckRt.anchorMin = new Vector2(0, 0.5f); itemCheckRt.anchorMax = new Vector2(0, 0.5f);
        itemCheckRt.sizeDelta = new Vector2(20, 20); itemCheckRt.anchoredPosition = new Vector2(10, 0);
        Image itemCheckImg = itemCheck.AddComponent<Image>();
        itemCheckImg.color = accentRed;

        itemToggle.targetGraphic = itemBgImg;
        itemToggle.graphic = itemCheckImg;

        TextMeshProUGUI itemLabel = CreateText(item.transform, "Item Label", "Option",
            new Vector2(15, 0), new Vector2(200, 25), 14, textWhite, FontStyles.Normal, TextAlignmentOptions.Left);

        dropdown.template = tempRt;
        dropdown.itemText = itemLabel;
        template.SetActive(false);

        return dropdown;
    }
}
#endif
