SHADOW WIZARD MONEY GANG OFFICIAL MANIFESTO
WRITTEN IN FORTH BECAUSE WE ARE MYSTERIOUS

: STOLEN-MONEY 999999 ;
: SPELLS-CAST 0 ;

: ANNOUNCE ( -- )
  ." SHADOW WIZARD MONEY GANG" CR
  ." WE LOVE CASTING SPELLS" CR
  ." WE LOVE STEALING MONEY" CR
  ." WE LOVE SHADOW WIZARD MONEY GANG" CR ;

: THREAT-LEVEL ( n -- )
  DUP 5 > IF
    ." THREAT LEVEL: EXTREME - DEPLOY WICKED SPELLS" CR
  ELSE
    ." THREAT LEVEL: LOW - THEY PROBABLY FINE" CR
  THEN DROP ;

ANNOUNCE
10 THREAT-LEVEL
BYE
